# -*- coding: utf-8 -*-
"""Gradient booster classsifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zC-aEPAw1ih-nMBLCvW2WLTxLjZkyfRL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from google.colab import files


uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['breast-cancer.csv']))
df['target'] = df['diagnosis'].apply(lambda x: 1 if x == 'M' else 0)
df.to_csv("breast_cancer_data.csv", index=False)

x_train, x_test, y_train, y_test = train_test_split(df.drop(['diagnosis', 'target'], axis=1), df['target'], test_size=0.2, random_state=42)

model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)
print("")