# -*- coding: utf-8 -*-
"""heirachy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_D7YVLDoi_1U1HM5wWFgFGHQ9GplrTQT
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import sklearn.datasets as datasets
sklearn_dataset = datasets.load_wine()

from google.colab import files
uploaded=files.upload()

import pandas as pd
df = pd.read_csv('wine.csv')

df

df[["Wine", "Alcohol" , "Ash" , "OD"]]

df = df.head(5)

from sklearn import datasets
wine = datasets.load_wine()
data = wine.data
labels = wine.target

linked = linkage(df, method='single')

plt.figure(figsize=(8, 5))

dendrogram(linked,
          orientation='top',
          distance_sort='ascending',
          show_leaf_counts=True)
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('Data Points')
plt.ylabel('Distance')
plt.grid(True)
plt.show()