# -*- coding: utf-8 -*-
"""Logistic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_VvddvqbKBOGxiEBg4w2hetlFwGeTQq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('purchase.csv')

df['Purchased'] = df['Purchased'].map({'Yes': 1, 'No': 0})

x = df['Income'].values / df['Income'].max()

r = 3.7
x0 = np.mean(x)
n_iterations = len(df)

values = [x0]
for _ in range(n_iterations):
    x_next = r * values[-1] * (1 - values[-1])
    values.append(x_next)

df['Logistic_Value'] = values[1:]

print(df)

plt.figure(figsize=(8,5))
plt.plot(range(1, n_iterations+1), df['Logistic_Value'], marker='o', label='Logistic Recursion')
plt.scatter(range(1, n_iterations+1), df['Purchased'], color='red', label='Purchased (1=Yes, 0=No)')
plt.title("Logistic Recursion vs Purchase Data")
plt.xlabel("Iteration (Row Number)")
plt.ylabel("Value / Purchase")
plt.legend()
plt.grid(True)
plt.show()