# -*- coding: utf-8 -*-
"""Random Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfllkRH8ht3nBYXOTdx7ZtG18fAwoltk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

from google.colab import files


uploaded = files.upload()

df=pd.read_csv('purchase.csv')

df

le =LabelEncoder()
df['Age_n']=le.fit_transform(df['Age'])
df['Gender_n']=le.fit_transform(df['Gender'])
df['Income_n']=le.fit_transform(df['Income'])
df['Education_n']=le.fit_transform(df['Education'])
df['Marital Status_n']=le.fit_transform(df['Marital Status'])
df['Purchased_n']=le.fit_transform(df['Purchased'])

df

df=df.drop(['Age','Gender','Income','Education','Marital Status','Purchased'],axis=1)

df

independant_var=df.drop(['Purchased_n','ID',],axis='columns')
dependant_var=df['Purchased_n']

x_train,x_test,y_train,y_test=train_test_split(independant_var,dependant_var,test_size=0.3,random_state=42)



from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy *100:.2f}%")

new_data = [[
    25,
    1,
    50000,
    1,
    0,
    0,
]]

prediction = model.predict(new_data)
print("prediction (0 = No, 1 = Yes):",prediction[0])

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

tree = model.estimators_[0]

plt.figure(figsize=(20, 10))

feature_names = independant_var.columns

plot_tree(
          feature_names=feature_names,
          class_names=['No', 'Yes'],
          filled=True,
          rounded=True)
plt.show()